### PR TITLE
feat!: Use async await instead of dispatchqueue which requires swift5.7 I think

### PR DESCRIPTION
**Pull request by doozMen**
I recently was baffled as my last log in async running code did not log. This was due to me using `AsyncParsableCommand` which ends before the log succeeds.

I'm discussing if this is a good idea but would like to have your feedback if you think this too [Swift-log API add async await to avoid problems in async code - Evolution / Pitches - Swift Forums](https://forums.swift.org/t/swift-log-api-add-async-await-to-avoid-problems-in-async-code/62913)

### CODE REVIEW

**Review by sushichop — COMMENTED** [review]
Thanks for letting me know this.

**Comment by sushichop** [comment]
@doozMen 
Thanks for letting me know this.

In the future, I would like to use the Swift Concurrency feature instead of DispatchQueue. I have actually considered this a few times, but I don't have the best way to simply achieve this for now. That's why Puppy uses serial DispatchQueue internally.

I skimmed your code, but unfortunately I don't think this will work correctly.　This is because the order of execution of two or more Tasks is non-deterministic. 
In fact, Puppy uses serial DispatchQueue internally to guarantee the execution order.
When you use Task, I think it is probably necessary to keep using single Task for each logger lifetime .

This discussion of execution order in Swift Concurrency is often discussed in the Swift Forum.
https://forums.swift.org/t/task-is-order-of-task-execution-deterministic/51553

Anyway when I have time, I also would like to explore how to achieve this.

Thanks🙂

**Comment by doozMen** [comment]
Thanks I'm also stil exploring async await. So thanks for your feedback. The order I have not considered. I will have a look at the discussion.

**Comment by doozMen** [comment]
I have read the problems with the task order and I think they do not apply to what I have build here. Let me clarify based on the answer from @ktoso

Task order is garanteed for structured concurrency if you keep the tasks inside the structure. You break the structure if you go and fire of tasks like `Task { ...}` .

So the following code if written in main would fail to have order

```swift
#!/usr/bin/env swift
import Foundation

Task {
  print("Task 1")
  sleep(10)
  print("Task 1 done")
}

Task {
  print("Task 2")
  sleep(5)
  print("Task 2 done")
}

print("main done")

```

> Note: You can put this in a swift file name it and then make it exe `chmod +x <#name#>.swift and run it `./<#name#>.swift`

The interesting thing is the output:

```
Task 1
main done
Task 2
```

As you can see execution order is wrong and the program exits premature. But the thing we did prove is that `Task{}` works similar to `Dipatchqueue.global.async { }` as the main ends before the tasks complete.

To fix both order and task execution we should wait for the value putting the async behaviour into the structure of the main runloop. We could do this by waiting for the value.

```swift
#!/usr/bin/env swift
import Foundation

func task1() async {
 let task1 = Task {
    print("Task 1")
    sleep(10)
    print("Task 1 done")
  }
  await task1.value
}

func task2() async {
  let task2 = Task {
    print("Task 2")
    sleep(5)
    print("Task 2 done")
  }
  await task2.value
}

await task2()
await task1()

print("main done")
```

This will output

```bash
Task 2
Task 2 done
Task 1
Task 1 done
main done
```

To make it again execute without the order we should explicitly do so with an `async let`

so change the task kick off to 

```swift
async let task1Result: () = task1()
async let task2Result: () = task2()

_ = await [task2Result, task1Result]
```

Which would let task 2 finish even do task 1 was started before 2.

```bash
Task 1
Task 2
Task 2 done
Task 1 done
main done
```

This is why in this proposal all the dispatchqueue code was removed as like you mention and also the debate mentions there is no way to go from unstructured async code, like `.sink {}` to structured async await. This is why my code does not contain loose `Task{}` declarations and I wait for the result like inside a function marked with async.

So although I agree that your remark is correct that we should be very careful with order. I think that my PR proves that it maintains the order and simplifies the code as it marks every function with async, there where before a hidden `Dispatchqueue.global.async { } ` was hiding inside an async log function.

So I still think my PR solves the issue and introduces correct usage of async await.

Please let me know what you think.

**Comment by doozMen** [comment]
So although I get that you would not want async code to wait for the log to complete, but you do want the log to complete before the main runloop exits.

So that is why I added a sempahore to the sync running code. Maybe this could be optional?

I do agree that something @ktoso talsk about to have a common actor that you could tell to do a task but still have the ability to wait for that actor to complete be more ideal, but this the language does not support.

I think that given the above it is still valid to warn the user of the fact that the log could not complete before program ends and offer a solution of the semaphore?

**Comment by doozMen** [comment]
It looks to mee a good followup for this pr or improvement to this PR would be to use https://github.com/dfed/swift-async-queue.git so that logging could happen without waiting, like in my PR now but it would offer you a way to wait for all the logs to finish before a program exits.

If you agree I could alter my PR in my spare time to have this?

**Comment by doozMen** [comment]
Ok so based on your comments and the discussion https://forums.swift.org/t/swift-log-api-add-async-await-to-avoid-problems-in-async-code/62913/2 I agree that the order is important but the bug I tried to solve remains. Puppy lacs the ability to wait for all logs to finish.

In my last commit I added this function to puppy that allows to wait for the logs to have finished using  [dfed/swift-async-queue: A queue that enables ordered sending of events from synchronous to asynchronous code](https://github.com/dfed/swift-async-queue).

In my project this works. Does this seam like something that would work for you?

**Comment by sushichop** [comment]
Sorry for the late response.
In short, did you encounter the main function process ending before the logging process was finished?
TBH, this was expected behavior for me and I originally thought that the application should handle it😅
However, it is also true that I did not write this idea in the README...:innocent:

Now, my understanding is that what you are asking for is a way to know that the logging process is complete. For example, you want a method to know about the above notification or to flush the log message, right?
I have just recently received a similar request, and I will add an optional feature of the library when I have time to spare.

Thanks.

**Review by sushichop — COMMENTED** [review]
Thanks.
I want to keep the library simple, so I will use AsyncStream directly if is needed.

**Pull request closed without merging**
